[package]
name = "thermite2_os"
version = "0.1.0"
authors = ["Stallmanifold <stallmanifold@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"